name: z_mart
description: "A new Flutter project."

publish_to: 'none'

version: 0.0.5+1

environment:
  sdk: '>=3.3.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  change_app_package_name: ^1.1.0

  #------------Utility Packages-----------#
  web: ^0.4.0
  http: ^1.2.0
  intl: ^0.19.0
  logger: ^2.0.2+1
  lottie: ^3.1.0
  url_launcher: ^6.2.4
  connectivity_plus: ^5.0.2
  flutter_native_splash: ^2.3.10
  smooth_page_indicator: ^1.1.0

  #  -------- Icons-------
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.6

  #-----------State management--------
  get: ^4.6.6
  get_storage: ^2.1.1

  #  ----Product Specific
  readmore: ^2.2.0
  carousel_slider: ^4.2.1
  flutter_rating_bar: ^4.0.1

  # --- Firebase
  firebase_core: ^2.26.0
  firebase_auth: ^4.17.7
  cloud_firestore: ^4.15.7




dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0


flutter:
  uses-material-design: true

  #---------------Local Assets----------
  assets:
    - assets/logos/
    - assets/images/
    - assets/images/onboarding_images/
    - assets/images/animations/
    - assets/icons/
    - assets/icons/categories/
    - assets/icons/brands/
    - assets/images/banners/
    - assets/images/products/
    - assets/images/user/


  #    --------Local Fonts---------
  fonts:
    - family: Poppins
      fonts:
      - asset: assets/fonts/Poppins-Light.ttf
        weight: 300
      - asset: assets/fonts/Poppins-Regular.ttf
        weight: 400
      - asset: assets/fonts/Poppins-Italic.ttf
        style: italic
      - asset: assets/fonts/Poppins-Medium.ttf
        weight: 500
      - asset: assets/fonts/Poppins-MediumItalic.ttf
        weight: 500
        style: italic
      - asset: assets/fonts/Poppins-SemiBold.ttf
        weight: 600
      - asset: assets/fonts/Poppins-Bold.ttf
        weight: 800