// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_HMCZLQ4gUfFzU2CZ83_XHo3mC1bqpzg',
    appId: '1:509927479665:web:607c5117cd16191157fed0',
    messagingSenderId: '509927479665',
    projectId: 'z-mart-10f28',
    authDomain: 'z-mart-10f28.firebaseapp.com',
    storageBucket: 'z-mart-10f28.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJ7BH2GGLpYvx7USMVGjUC-IUev67tc5U',
    appId: '1:509927479665:android:2f933830a2a4a0b557fed0',
    messagingSenderId: '509927479665',
    projectId: 'z-mart-10f28',
    storageBucket: 'z-mart-10f28.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDf4OTmicOOHyznEe6fP6QxEo6TDlXlcU4',
    appId: '1:509927479665:ios:07968d13b0351a9157fed0',
    messagingSenderId: '509927479665',
    projectId: 'z-mart-10f28',
    storageBucket: 'z-mart-10f28.appspot.com',
    androidClientId: '509927479665-q1rd10g4uiidpbkh2tclapuib38lpeku.apps.googleusercontent.com',
    iosClientId: '509927479665-8cbbe7q1ldkp37nhbmflappe5af7697b.apps.googleusercontent.com',
    iosBundleId: 'com.example.zMart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDf4OTmicOOHyznEe6fP6QxEo6TDlXlcU4',
    appId: '1:509927479665:ios:db9928b4ac0b01f157fed0',
    messagingSenderId: '509927479665',
    projectId: 'z-mart-10f28',
    storageBucket: 'z-mart-10f28.appspot.com',
    androidClientId: '509927479665-q1rd10g4uiidpbkh2tclapuib38lpeku.apps.googleusercontent.com',
    iosClientId: '509927479665-jcpfka1hplo5nu9qf4cf8esc95i7u0l4.apps.googleusercontent.com',
    iosBundleId: 'com.example.zMart.RunnerTests',
  );
}
